
-- SCHEMA

DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE
(
    MESSAGE_ID   TEXT,

    CHANNEL_ID TEXT,
    CHANNEL_NAME TEXT,
    CHANNEL_TITLE TEXT,

    SENDER_USERNAME TEXT,
    SENDER_ID TEXT,

    PUBLISH_DATE DATE,
    CONTENT      TEXT NOT NULL,
    PRIMARY KEY (MESSAGE_ID, CHANNEL_NAME)
);

CREATE INDEX DATE_CHANNEL_INDX on MESSAGE (CHANNEL_ID, PUBLISH_DATE);
CREATE INDEX DATE_INDX on MESSAGE (PUBLISH_DATE);

DROP TABLE IF EXISTS ONO_ANCHORS;
CREATE TABLE ONO_ANCHORS
(
    CHANEL_NAME     TEXT PRIMARY KEY,
    LAST_MESSAGE_ID TEXT DEFAULT 'NOT_SET'
);

DROP TABLE IF EXISTS USER_CHANNEL;
CREATE TABLE USER_CHANNEL
(
    CHANEL_NAME TEXT,
    USER_ID     TEXT,
    PRIMARY KEY (CHANEL_NAME, USER_ID)
);

-- INITIAL POPULATE

INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('rian_ru');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('novosty');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('topor');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('meduzalive');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('meduzaevening');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('navalny');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('politika');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('russica2');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('russicatop');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('proeconomics');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('mediatech');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('redzion');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('incnews');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('tolk_tolk');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('scienpolicy');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('actual_comment');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('WCIOMofficial');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('birmanalex');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('karaulny');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('malzoffsgallery');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('CyberLeninka');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('breakingmash');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('ru_FTP');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('lentachold');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('MRZLKVK');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('varlamov_news');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('directorate4');

INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('rospres');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('DavydovIn');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('kremlin_mother_expert');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('mislinemisli');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('metodi4ka');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('politjoystic');
INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('kbrvdvkr');


-- INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('AlexanderLuchko');
-- INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('kinmanz');
-- INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('sns_internships');
-- INSERT INTO ONO_ANCHORS(CHANEL_NAME) VALUES ('startupneversleeps');
